ENCODER_NUM_LAYERS = 20
HIDDEN_DIM = 128 # LayerId, NeuronId, Bias, Weights - up to 257
WEIGHT_DIM = HIDDEN_DIM - 3
MAX_NEURONS_NUM = WEIGHT_DIM
MAX_LAYERS = 5
COMPRESSOR_INTERNAL_FF_DIMENSION_COEEF = 2
NUM_HEADS = 8

#Formulas
FORMULA_EMPTY = 0
FORMULA_SIN = 1
FORMULA_COS = 2
FORMULA_LOG = 3
FORMULA_EXP = 4
FORMULA_MAX = FORMULA_EXP
