FILE_KIND = "File"
DOCUMENT_KIND = "Document"
UNKNOWN_KIND = "Unknown"
DIRECTORY_KIND = "Directory"
QUESTIONS_FIELD = "questions"
KIND_FIELD = "kind"
DESCRIPTION_FIELD = "description"
SHORT_DESCRIPTION_FIELD = "short_description"
PATH_FIELD = "path"
KEYWORDS_FIELD = "keywords"
BROKEN_KIND = "broken"
NODE_1 = "node_1"
NODE_2 = "node_2"
EDGE = "edge"

PROJECT_DESCRIPTION_ID = "__PROJECT_DESCRIPTION__"
FOLDERS_TO_EXCLUDE_ID = "__FOLDERS_TO_EXCLUDE__"
MAIN_TOPICS_ID = "__MAIN_TOPICS__"
QUESTIONS2FILES_ID = "__QUESTIONS2FILES__"
QUESTIONS2FILES_CHECKED_ID = "__QUESTIONS2FILES_CHECKED__"

MAX_ITEMS_IN_REQUEST = 10

NORMAL_TEXT = 1
SELECTED_TEXT = 2
ITEM_TO_HIGHLIGHT = 3

DB_FILE_NAME = "knowledge.db"

MAX_CONVERSATION_STEPS = 5