FILE_KIND = "File"
DIRECTORY_KIND = "Directory"
QUESTIONS_FIELD = "questions"
KIND_FIELD = "kind"
DESCRIPTION_FIELD = "description"
PATH_FIELD = "path"
BROKEN_KIND = "broken"
NODE_1 = "node_1"
NODE_2 = "node_2"
EDGE = "edge"
MAIN_TOPICS_ID = "__MAIN_TOPICS__"
MAX_ITEMS_IN_REQUEST = 10

NORMAL_TEXT = 1
SELECTED_TEXT = 2
ITEM_TO_HIGHLIGHT = 3
